[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.19.5"
  NPM_VERSION = "10.8.2"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200